# Generated by Django 4.1.13 on 2023-11-14 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clients',
            fields=[
                ('clientId', models.AutoField(primary_key=True, serialize=False)),
                ('clientName', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='events',
            fields=[
                ('eventId', models.AutoField(primary_key=True, serialize=False)),
                ('eventName', models.CharField(max_length=500)),
            ],
        ),
    ]
