# Generated by Django 4.1.13 on 2023-11-14 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypartyApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='clientName',
            field=models.CharField(max_length=30),
        ),
    ]
