# Generated by Django 4.1.13 on 2023-11-15 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypartyApp', '0002_alter_clients_clientname'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='clientPass',
            field=models.TextField(default='DEFAULT VALUE', max_length=500),
        ),
        migrations.AddField(
            model_name='clients',
            name='eventCPF',
            field=models.TextField(default='DEFAULT VALUE', max_length=500),
        ),
        migrations.AddField(
            model_name='clients',
            name='eventNumber',
            field=models.TextField(default='DEFAULT VALUE', max_length=500),
        ),
        migrations.AddField(
            model_name='events',
            name='eventCEP',
            field=models.TextField(default='DEFAULT VALUE', max_length=500),
        ),
        migrations.AddField(
            model_name='events',
            name='eventFim',
            field=models.TextField(default='DEFAULT VALUE', max_length=500),
        ),
        migrations.AddField(
            model_name='events',
            name='eventInicio',
            field=models.TextField(default='DEFAULT VALUE', max_length=500),
        ),
        migrations.AddField(
            model_name='events',
            name='eventLocal',
            field=models.TextField(default='DEFAULT VALUE', max_length=500),
        ),
        migrations.AddField(
            model_name='events',
            name='eventProdutor',
            field=models.TextField(default='DEFAULT VALUE', max_length=500),
        ),
    ]
