# Generated by Django 4.1.13 on 2023-11-16 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypartyApp', '0003_clients_clientpass_clients_eventcpf_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clients',
            old_name='eventCPF',
            new_name='clientCPF',
        ),
        migrations.RenameField(
            model_name='clients',
            old_name='eventNumber',
            new_name='clientNumber',
        ),
        migrations.AddField(
            model_name='clients',
            name='clientEmail',
            field=models.EmailField(default='DEFAULT VALUE', max_length=500),
        ),
    ]
